[package]
name = "rbx-dom-napi"
version = "0.1.0"
edition = "2021"
publish = false
description = "N-API bindings for the rbx-dom libraries"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.12.1", default-features = false, features = ["napi4", "dyn-symbols", "serde-json"] }
napi-derive = "3.6.3"
rbx_binary = { path = "../upstream/rbx-dom/rbx_binary", features = ["unstable_text_format"] }
rbx_dom_weak = { path = "../upstream/rbx-dom/rbx_dom_weak" }
rbx_reflection = { path = "../upstream/rbx-dom/rbx_reflection" }
rbx_reflection_database = { path = "../upstream/rbx-dom/rbx_reflection_database", features = ["debug_always_use_bundled"] }
rbx_types = { path = "../upstream/rbx-dom/rbx_types", features = ["serde"] }
rbx_xml = { path = "../upstream/rbx-dom/rbx_xml" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[build-dependencies]
napi-build = "2.4.1"
