/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Attributes {
  constructor(valueJson?: string | undefined | null)
  get(key: string): string | null
  set(key: string, valueJson: string): string | null
  remove(key: string): string | null
  clear(): void
  length(): number
  isEmpty(): boolean
  toJson(): string
  encode(): Buffer
}

export declare class Dom {
  constructor(specJson: string)
  static fromRaw(rawJson: string): Dom
  snapshot(): string
  rootRef(): string
  sourceReferents(): string
  root(): string
  rootMut(): Instance
  instance(referent: string): string | null
  instanceObject(referent: string): Instance | null
  raw(): string
  rawInstances(): string
  children(referent: string): Array<string>
  descendants(referent?: string | undefined | null): string
  ancestorsOf(referent: string): string
  fullPath(referent: string, separator?: string | undefined | null): string
  getProperty(referent: string, property: string): string | null
  uniqueId(referent: string): string | null
  setProperty(referent: string, property: string, valueJson: string): void
  removeProperty(referent: string, property: string): boolean
  setName(referent: string, name: string): void
  setClass(referent: string, className: string): void
  insert(parent: string, specJson: string): string
  insertBuilder(parent: string, builder: InstanceBuilder): string
  reserve(additional: number): void
  destroy(referent: string): void
  cloneWithin(referent: string): string
  transferWithin(referent: string, parent: string): void
  transfer(referent: string, destination: Dom, parent: string): void
  cloneIntoExternal(referent: string, destination: Dom): string
  cloneMultipleIntoExternal(referents: Array<string>, destination: Dom): Array<string>
  view(): string
  toXml(optionsJson?: string | undefined | null): Buffer
  toBinary(optionsJson?: string | undefined | null): Buffer
  toXmlWithDatabase(database: ReflectionDatabase, optionsJson?: string | undefined | null): Buffer
  toBinaryWithDatabase(database: ReflectionDatabase, optionsJson?: string | undefined | null): Buffer
  instanceCount(): number
}

export declare class DomViewer {
  constructor()
  view(dom: Dom): string
  viewChildren(dom: Dom): string
}

export declare class Instance {
  referent(): string
  parent(): string
  children(): Array<string>
  name(): string
  className(): string
  snapshot(): string
  properties(): string
  getProperty(property: string): string | null
  setProperty(property: string, valueJson: string): void
  removeProperty(property: string): boolean
  setName(name: string): void
  setClass(className: string): void
}

export declare class InstanceBuilder {
  constructor(className?: string | undefined | null, propertyCapacity?: number | undefined | null)
  referent(): string
  className(): string
  name(): string
  setClass(className: string): void
  setName(name: string): void
  setReferent(referent: string): void
  hasProperty(property: string): boolean
  getProperty(property: string): string | null
  setProperty(property: string, valueJson: string): void
  addProperty(property: string, valueJson: string): void
  addChild(child: InstanceBuilder): void
}

export declare class ReflectionDatabase {
  constructor(databaseJson?: string | undefined | null)
  static fromApiDump(apiDumpJson: string): ReflectionDatabase
  version(): Array<number>
  classNames(): Array<string>
  enumNames(): Array<string>
  toJson(): string
  class(name: string): string
  property(className: string, propertyName: string): string
  defaultProperty(className: string, propertyName: string): string
  propertyNames(className: string): Array<string>
  enum(name: string): string
  enumItems(name: string): string
  isA(className: string, superclassName: string): boolean
  superclasses(className: string): Array<string>
}

export declare function attributesDecode(data: Buffer): Attributes

export declare function attributesEncode(valueJson: string): Buffer

export declare function axesAll(): string

export declare function axesBits(valueJson: string): number

export declare function axesContains(valueJson: string, otherJson: string): boolean

export declare function axesEmpty(): string

export declare function axesFromBits(bits: number): string

export declare function binaryString(data: Buffer): Buffer

export declare function bindingMetadata(): string

export declare function brickColorByName(name: string): string

export declare function brickColorByNumber(number: number): string

export declare function brickColorToColor3uint8(valueJson: string): string

export declare function cframeFromMatrix(positionJson: string, xJson: string, yJson: string, zJson: string): string

export declare function cframeFromPosition(positionJson: string): string

export declare function cframeIdentity(): string

export declare function color3(r: number, g: number, b: number): string

export declare function color3uint8(r: number, g: number, b: number): string

export declare function colorSequence(keypointsJson: string): string

export declare function colorSequenceKeypoint(time: number, colorJson: string): string

export declare function contentId(value: string): string

export declare function contentIdValue(valueJson: string): string

export declare function contentKind(valueJson: string): string

export declare function contentNone(): string

export declare function contentObject(referent: string): string

export declare function contentObjectValue(valueJson: string): string | null

export declare function contentUri(uri: string): string

export declare function contentUriValue(valueJson: string): string | null

export declare function convertFile(data: Buffer, fromFormat: string, toFormat: string, optionsJson?: string | undefined | null): Buffer

export declare function createDom(specJson: string): Dom

export declare function createDomFromRaw(rawJson: string): Dom

export declare function enumItem(ty: string, value: number): string

export declare function enumValue(value: number): number

export declare function facesAll(): string

export declare function facesBits(valueJson: string): number

export declare function facesContains(valueJson: string, otherJson: string): boolean

export declare function facesEmpty(): string

export declare function facesFromBits(bits: number): string

export declare function font(family: string, weight: number, style: number): string

export declare function fontParts(valueJson: string): string

export declare function fontRegular(family: string): string

export declare function materialColorsDecode(data: Buffer): string

export declare function materialColorsDefault(): string

export declare function materialColorsEncode(valueJson: string): Buffer

export declare function materialColorsGet(valueJson: string, material: string): string

export declare function materialColorsSet(valueJson: string, material: string, colorJson: string): string

export declare function matrixBasicRotationId(valueJson: string): number | null

export declare function matrixFromBasicRotationId(id: number): string

export declare function matrixTranspose(valueJson: string): string

export declare function netAssetRef(data: Buffer): string

export declare function netAssetRefData(valueJson: string): Buffer

export declare function netAssetRefHash(data: Buffer): string

export declare function netAssetRefHashBytes(valueJson: string): Buffer

export declare function numberRange(min: number, max?: number | undefined | null): string

export declare function numberSequence(keypointsJson: string): string

export declare function numberSequenceKeypoint(time: number, value: number, envelope: number): string

export declare function physicalProperties(density: number, friction: number, elasticity: number, frictionWeight: number, elasticityWeight: number, acousticAbsorption: number): string

export declare function physicalPropertiesDefault(): string

export declare function physicalPropertiesParts(valueJson: string): string | null

export declare function ray(originJson: string, directionJson: string): string

export declare function readBinary(data: Buffer, optionsJson?: string | undefined | null): Dom

export declare function readBinaryWithDatabase(data: Buffer, database: ReflectionDatabase, optionsJson?: string | undefined | null): Dom

export declare function readXml(data: Buffer, optionsJson?: string | undefined | null): Dom

export declare function readXmlWithDatabase(data: Buffer, database: ReflectionDatabase, optionsJson?: string | undefined | null): Dom

export declare function rect(minJson: string, maxJson: string): string

export declare function refFromString(value: string): string

export declare function refIsNone(value: string): boolean

export declare function refIsSome(value: string): boolean

export declare function reflectionClass(name: string): string

export declare function reflectionClassNames(): Array<string>

export declare function reflectionDatabase(): string

export declare function reflectionDatabaseFromBinary(data: Buffer): ReflectionDatabase

export declare function reflectionDefaultProperty(className: string, propertyName: string): string

export declare function reflectionEnum(name: string): string

export declare function reflectionEnumItems(name: string): string

export declare function reflectionEnumNames(): Array<string>

export declare function reflectionIsA(className: string, superclassName: string): boolean

export declare function reflectionLocalDatabasePath(): string | null

export declare function reflectionProperty(className: string, propertyName: string): string

export declare function reflectionPropertyNames(className: string): Array<string>

export declare function reflectionSuperclasses(className: string): Array<string>

export declare function reflectionVersion(): Array<number>

export declare function refNew(): string

export declare function refNone(): string

export declare function region3(minJson: string, maxJson: string): string

export declare function region3int16(minJson: string, maxJson: string): string

export declare function removeProperty(data: Buffer, format: string, className: string, propertyName: string, outputFormat?: string | undefined | null): Buffer

export declare function securityCapabilitiesBits(bits: string): string

export declare function sharedString(data: Buffer): string

export declare function sharedStringData(valueJson: string): Buffer

export declare function sharedStringHash(data: Buffer): string

export declare function sharedStringHashBytes(valueJson: string): Buffer

export declare function tagsDecode(data: Buffer): string

export declare function tagsEncode(tagsJson: string): Buffer

export declare function tagsIsEmpty(data: Buffer): boolean

export declare function tagsLength(data: Buffer): number

export declare function udim(scale: number, offset: number): string

export declare function udim2(xJson: string, yJson: string): string

export declare function uniqueId(index: number, time: number, random: string): string

export declare function uniqueIdNil(): string

export declare function uniqueIdNow(): string

export declare function uniqueIdParts(value: string): string

export declare function variant(valueJson: string): string

export declare function variantType(valueJson: string): string

export declare function vector2(x: number, y: number): string

export declare function vector2int16(x: number, y: number): string

export declare function vector3(x: number, y: number, z: number): string

export declare function vector3int16(x: number, y: number, z: number): string

export declare function vector3NormalId(valueJson: string): number | null

export declare function viewBinary(data: Buffer): string

export declare function viewBinaryText(data: Buffer): string
